[package]
name = "cr-sqlite-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rusqlite = { version = "0.37", features = ["bundled", "trace"] }
crsql_bundle = { path = "../core/rs/bundle" }
tempfile = "3.14.0"
